name: Compile and publish resume
on: push

jobs:
  compile:
    name: Compile resume
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run Docker container to compile latex
        uses: addnab/docker-run-action@v3
        with:
          image: kothiga/resume:latest
          options: -v ${{ github.workspace }}:/data
          run: pdflatex AustinKothig_resume.tex
      - name: Verify build
        run: ls -l AustinKothig_resume.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-latest
          path: AustinKothig_resume.pdf
  release:
    name: Release resume
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: resume-latest
    - name: Get version tag
      id: version
      run: echo "TAG_NAME=v$(TZ='America/Toronto' date '+%y.%m.%d')" >> $GITHUB_OUTPUT
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        files: AustinKothig_resume.pdf
